server:
  port: 8084
spring:
  rabbitmq:
    host: localhost
    username: leyou129
    password: 123456
    virtual-host: /leyou129
  thymeleaf:
    cache: false  #除去缓存
  application:
    name: page-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1  #指定实例的地址
    prefer-ip-address: true #上报给eureka的是ip，默认是主机名
logging:
  level:    #  debug   info  warn   error
    root: info   #其他的日志级别都是info
    com.leyou: debug # 我们乐优用debug
ly:
  static:
    itemDir: D:/leyou-code/428129/software/nginx-1.16.0/html/item #静态页服务器地址
    itemTemplate: item #模板名称