server:
  port: 8087
spring:
  application:
    name: auth-service
  redis:
    host: 127.0.0.1
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1  #指定实例的地址
    prefer-ip-address: true #上报给eureka的是ip，默认是主机名
logging:
  level:    #  debug   info  warn   error
    root: info   #其他的日志级别都是info
    com.leyou: debug # 我们乐优用debug
ly:
  jwt:
    pubKeyPath: D:\leyou-code\428129\rsakey\leyou_key.pub # 公钥地址
    priKeyPath: D:\leyou-code\428129\rsakey\leyou_key # 私钥地址
    cookie:
      expire: 30 #过期时间设置 单位分钟
      refreshTime: 10 # 判断token如果有效期还剩下10分钟内，我们重新生成一个新的token返回
      cookieName: LY_TOKEN # cookie名称
      cookieDomain: leyou.com # cookie的域