server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300  # 注意这里的端口是9300，这个端口是java客户端操作es的
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1  #指定实例的地址
    prefer-ip-address: true #上报给eureka的是ip，默认是主机名
logging:
  level:    #  debug   info  warn   error
    root: info   #其他的日志级别都是info
    com.leyou: debug # 我们乐优用debug