server:
  port: 10010
spring:
  application:
    name: api-gateway
  task:
    scheduling:
      pool:
        size: 2
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true  #允许预检请求
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://manage.leyou.com"  # 允许哪些域来访问
              - "http://manage.leyou.com:9001"  # 允许哪些域来访问
              - "http://www.leyou.com"  # 允许哪些域来访问
              - "http://www.leyou.com:9002"  # 允许哪些域来访问
              - "http://localhost:9001"  # 允许哪些域来访问
              - "http://localhost:9002"  # 允许哪些域来访问
            allowedHeaders:  # 运行的请求头信息
              - "*"
            allowCredentials: true  #允许携带cookie
            maxAge: 360000    #预检请求的有效期： 1个小时
            allowedMethods:  # 允许哪些方法跨域
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
              - HEAD
      routes:
        - id: item-service   # 路由id,可以随意写
          # 代理的服务地址；lb表示负载均衡(从eureka中获取具体服务)
          uri: lb://item-service
          # 路由断言，可以配置映射路径
          predicates:
            - Path=/api/item/**
          filters:
            # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=2
        - id: upload-service   # 路由id,可以随意写
          uri: lb://upload-service
          predicates:
            - Path=/api/upload/**
          filters:
            - StripPrefix=2
        - id: search-service   # 搜索微服务
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=2
        - id: user-service   # 用户微服务
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: auth-service   # 授权中心微服务
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    #下面的配置都是在开发阶段配置的： 生产环境走默认
    registry-fetch-interval-seconds: 5  #  从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
    instance-info-replication-interval-seconds: 5 # 实例信息替换的时间
    initial-instance-info-replication-interval-seconds: 5 #初始化实例替换的时间
ly:
  jwt:
    pubKeyPath: D:\leyou-code\428129\rsakey\leyou_key.pub # 公钥地址
    cookie:
      cookieName: LY_TOKEN # cookie名称
  filter:
    allowPaths:
      - /api/auth/login
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      #- /api/item