server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 新版本的驱动
    url: jdbc:mysql:///leyou129?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: passw0rd
mybatis:
  type-aliases-package: com.leyou.item.entity
  configuration:
    map-underscore-to-camel-case: true  #驼峰映射
  mapper-locations: mapper/*.xml
# 通用mapper的关键字增强: 如果碰到和mysql相关的关键字，会自动给关键字加上反引号
mapper:
  wrap-keyword: "`{0}`"
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1  #指定实例的地址
    prefer-ip-address: true #上报给eureka的是ip，默认是主机名
logging:
  level:    #  debug   info  warn   error
    root: info   #其他的日志级别都是info
    com.leyou: debug # 我们乐优用debug